### ISSUE TITLE
Add details for using the library?

### ISSUE THREAD

**Issue by IanQS** [spywhere/tmux-named-snapshot#1]
Can you add details for a "workflow"? I tried running your library via

```
<Prefix> - <C-m> 
```
which saved it, but didn't ask me where to save it or what to name it? 

and then when I tried 

```
<Prefix> - <C-m> 
```

it didn't actually restore(?) any state even though it said it did

P.s Thank you so much for doing this! I'm very excited to see this in its full form

**Comment by spywhere** [comment]
It's pretty much seamless from user experience. What it does is simply make a new snapshot (by calling tmux-resurrect) then link the `last` snapshot from tmux-resurrect and put it into a new one with specific name (then it restore the `last` snapshot back to the previous snapshot).

Name are coming from the key binding configurations, the default name it saved will be `manual`. Also, files are kept in the same location as tmux-resurrect (default is `$HOME/.tmux/resurrect`) thus no need to configure those separately from how tmux-resurrect works.

Save and restore have a different key binding though, default is `C-m` to save and `C-n` to restore. Making a toggle might be a bit more complicate. We could file another issue solely for that, but there is some certain cases that toggle might not work.

**Comment by IanQS** [comment]
Gotcha! Okay, I think I understand now. To make sure I understand, you're saying "create two keybindings where you've specified the name so that you can save and load a given named profile"? Assuming that's true, what file exactly should I change to handle the keybindings? Or would I do that within tmux itself? Apologies, I'm not very familiar with all of this

**Comment by spywhere** [comment]
What you need is simply set a value to tmux global variables according to the documentation in the readme. The variable name and its value is already documented in the readme of this repo itself.

For how to set a variable (usually refers as option) in tmux, I will leave you to check those out as it would be crucial for more customization, even out of this plugin scope.

**Comment by ShrutheeshIR** [comment]
Great plugin! How do I give it a name other than manual? And how do I restore it?

**Comment by spywhere** [comment]
Please check out the keybindings section on the README page. Both default name and keybindings for save and restore are already documented there. You can have multiple keybindings mapped to a different named snapshot though.

**Comment by javierdebug** [comment]
Hi, thank you for this plugin, this is something I was looking for.

I have a question about this topic, where should we add the keybindings for additional snapshots names? and can you provide an example line so we are sure how to write them? 
Thank you

**Comment by spywhere** [comment]
The configuration should be put in `.tmux.conf` file.

For example,

```
set -g @named-snapshot-save 'C-m:manual C-d:dev'
set -g @named-snapshot-restore 'C-n:manual C-D:dev'
```

this will setup the following keybindings...

- `Prefix + Ctrl-m`: Save 'manual' snapshot
- `Prefix + Ctrl-d`: Save 'dev' snapshot
- `Prefix + Ctrl-n`: Restore 'manual' snapshot
- `Prefix + Ctrl-D`: Restore 'dev' snapshot
