### ISSUE TITLE
Customization of save directory and fzf integration

### ISSUE THREAD

**Issue by Subjective** [spywhere/tmux-named-snapshot#2]
What do you think about allowing for customization of the save directory? It would make it really easy to search and pick sessions with fzf as opposed to having to memorize the name and type it out exactly.

**Comment by spywhere** [comment]
This plugin was trigger `tmux-resurrect` behind the scene, so all controls are respective to that plugin.

What you are looking for is probably this one, [Change a directory](https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/save_dir.md) where `tmux-resurrect` saves tmux environment

**Comment by Subjective** [comment]
Oh, I was thinking more along the lines of having separate save directories for named snapshots and normal resurrect sessions. 

But now that I think about it, there's probably a way to filter only symlinked files for fzf.

**Comment by spywhere** [comment]
Ah I see. I think that should be possible. I'll probably add the change in a few days as I'm quite busy during these period of time.

**Comment by Subjective** [comment]
Awesome! This could work really nicely with tmux popups:
![Screen Recording 2023-09-17 at 5 49 45 PM](https://github.com/spywhere/tmux-named-snapshot/assets/56745535/678b0f60-3aa6-4d6f-a3e0-50a5fb95998c)

This might require a bit more thought to flesh out, but perhaps there's a way to move all actions related to saving/restoring sessions to a single keybind. Here's a proposed workflow: 
1. Hit the keybind to list all sessions in a fzf popup. 
2. By default, whichever one is selected will be restored. 
3. But if a session isn't listed after typing its name into fzf, then a new one will be created of that name. 
4. And if the session name matches the one that is currently active, then the current named session will be saved.

**Comment by spywhere** [comment]
While I agree that integration with fzf would be great, it isn't a good idea to have fzf built-in since the workflow differs between users. Also, this is another dependency on the project (even an optional one) that would increase the project's maintainability. However I see that by providing a custom directory to keep the snapshot would ease the integration.

**Comment by spywhere** [comment]
Option `@named-snapshot-dir` added in [f380b22](https://github.com/spywhere/tmux-named-snapshot/commit/f380b22c687f7ad9707719136dd71fc6e95d9628)
