### ISSUE TITLE
Snapshot cannot be found be -r check in bash

### ISSUE THREAD

**Issue by ak1932** [spywhere/tmux-named-snapshot#3]
For some reason the plugin stopped working recently. After going through the source i figured out that the condition
```bash
if [ -r "$name_path" ] 
```
in restore snapshot script to find snapshot does not work anymore and gives snapshot not found error.
```bash
if [[ -L "$name_path" ]]
```
seems to work fine for now to check if the symbolic link is present or not.

**Comment by spywhere** [comment]
Close by #4
